sudo: false
language: node_js
notifications:
  email:
    on_success: change
    on_failure: always
node_js:
- 6.9.2
cache:
  directories:
    - node_modules
before_script:
- npm install -g gulp
script:
- source read.version.sh
- echo $PACKAGE_JSON_VERSION
- npm run injectTag
- npm run build
- npm run minimize
- npm run test
- npm run uploadCoverage
- npm run testChunks
after_success:
- npm run doc
- if [ "x$TRAVIS_TAG" != "x" ]; then bash ./deploy.doc.sh ; fi
- npm run docsitemap
- npm run zipForGitReleases
env:
  global:
  - COMMIT_AUTHOR_EMAIL: sandbox_JSUI@coveo.com
deploy:
  - provider: npm
    email: sandbox_JSUI@coveo.com
    skip_cleanup: true
    api_key:
      secure: SuOyfDTjg+Z1qSMVPEuiwDLmjEsQ3PFE0Ue4hTpkyWFKlA13P1/uho0BGbtmQIAgtz5lpv+bgo/pa4iE7WDUcPht1XYlrHCKkfLj117rfTLOZKlv2QnFCZYkWKAeZBKzbKaTZLMlybgVn0hzKwwt5teKz7PvjF384lmaFEiTw1y6Ru+dYttuG8VkuxctM7qXe/omuyNEFJg1kLW5vdpO6QlESSdF+g0zHfo8ubXB+DXXM6oYSV8EOuBFqeACFvI3vLZuhdz4ROG/ayz/5QMWHK2wDi5hPycCEOTx6VeUcBg74ZL0dLHiIjN4cTXWgOuwtxCG2Sqw8MYsCRrBkarwNy4Eez8DAId6otLiPQ+qDOZ7+AO8tY7kzj/1ABkL4CipSe0ob/FLai9GzR+wISODROO9MzOu+cLnioLCwpukz8zICeDSwH3tAPbJYDLQr8sSb8/uFstkIBlmRyVt2WNNuaRQecZH7PjiaINNkeC0N7yUB6pGdyqC9SPxWgSlnA5inf5PpBjL9LouIsF5EuMC87WxXfKfhg2lrY2TPvueyV145wcu8rUk/WYlTqaDRCQSiFYIQdOQfGaDzFx0dsSEGr38hFe+oAofdosR/W/CW2fdjkxbB9Zfka9ygV1Lb2GQUGzHoOS2xs01mwGlm4LiM7o1kE1WYpY+6XMfv7icYRw=
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "! $TRAVIS_TAG =~ .*beta.*"
  - provider: script
    script: node deploy.beta.js
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$TRAVIS_TAG =~ .*beta.*"
  - provider: releases
    api_key:
      secure: jKNS2mWnLUP5kQkjApoIFxQVXAr8ed3nsTIltY6gOvf1/2kbkS0WbzR7Km9lewFA2ZEBSFAu/ek+ewXjEx8FVQAe3CeCS1sS5RVqU/2YvFGBPYzzVw1l3FOJkQsvruRc7UzkznXbLvk+7LerHDpsy3p6ut8stMokztiq8QyWN+GHhrB/QgBQV/swPx40QknAIXndtLEPQfttukLowAdH9ml2BgrgE0/3iitmja/8eIQxVT6dlFyXYV+iU44kPyS595wM7eakUGXNFB2W9sUZ9IY/8lUqPz85G3FkKyiPv3SZJRs158/32+vvdXAtT/wtHjP5PqESPv/pL31M9IpQYYIdTSPwUZtOdRZ6JrxV/xusQ2Nm5p3qNrKgtkEZ921BGHJEMK9xs0yAhMuT39JLhoZE30g8SXokWQWi6WzrRELODYubVMaXTmfgv2ZZN4T3B8xNSabmE3Jm7Gj5Lb9wdR+pbWxPlB475i4H7grOHAN9xRIWokAIIN9RuTPRx1XuxhLUI9BH/GrJXNZbv1800rqF15W9Yuw1RqMfrSWq2snyDalXW3gLHYeAFAP1hfD2mU1zySjP/HQ6VkCwmgCjlAg4W5xK4NlXX0C/EIkoLKhSefxLdhquMZQTION+v0fOvl7Kdz17vt231dEIjNZxsBlLL+JZoxOZA5tVRDMNbko=
    file_glob: true
    file:
      - "search-ui.zip"
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
  - provider: s3
    access_key_id: AKIAIWWGBULVXLZH3XUQ
    secret_access_key:
      secure: rE1I0tkPU4n9e6bjm+eAujC1ttRTGtDjOvyYIyz/0K62n7pZ8IRAH/5AIHKrNbbGu0ImQrrz8owP/jamhk5AN9+9ISrqe/jTtid9garlnfrgQtvZJNw6jVcqj9WXycz7nFLLyArPR9oXHa7GSbwk8yjn0Ho216Xf1FNGq71Jv4sCEkwfvUwi9Hs427K6p09s/dsf/q04+hZVASc1L4CMLgTj5BBOPPP9cw7QusHYCaviyy0tCtiNq5tt+R64DfNTY4mbg3wIMp4ouyfxkKYCpVngoWBm+dFtH2p3SJnTPullvEm6HA/domQHlCzsUXles4rsBZ3/8Rb1xUteqdlthyt0+WC8vpip5gsPDwk/+GcD+bVoBPCIUbQxVjmSSuZ7heJz5aPQOg0t23u/nZ2mYdXR6xjpocaf7awtAMm1lHfvQkV0SUKMNVMH2rYEfRYuans0edleVaBTri2VSCzXwqrNd7q+LcWJdxHfibXunQ3x7eQuWaLY2rw+VKHQTdwvPKjw9eqioiTN7HEhKoZn+bYU0M3XimuE9DKo7MRWXRkFvNSAQkbFRA45/nSgh317nHuXmyelyFm/Teqqy7zZYPctJ+yJD1QRvRv2kBnev/G6p6466JMLpQVQw4JzUhU9X5hyGYaCeDROHOnRoWLngDUuN9vs1v4O7M/PSeJMsdg=
    bucket: coveo-nprod-binaries
    local-dir: bin
    upload-dir: proda/StaticCDN/searchui/v$PACKAGE_JSON_VERSION
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "! $TRAVIS_TAG =~ .*beta.*"

branches:
  only:
    - master
    - /^.*release.*$/1
    - /2\.[0-9]+\.[0-9]+/
